// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";
import path from "node:path";

dotenv.config({ path: path.resolve(__dirname, ".env") });
if (process.env.NODE_ENV === "test") {
  dotenv.config({ path: path.resolve(__dirname, ".env.test"), override: true });
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url:
      process.env.NODE_ENV === "test"
        ? process.env["DATABASE_URL_TEST"]
        : process.env["DATABASE_URL"],
  },
});
